name: time-quote
version: 1.9.0.0

dependencies:
  - base
  - template-haskell
  - time == 1.9.*

ghc-options: -Wall -Werror

library:
  source-dirs: src/
  exposed-modules:
    - Data.Time.Quote

tests:
  doctest:
    main: doctest-driver.hs
    source-dirs: test/
    ghc-options: -threaded
    dependencies:
      - base
      - doctest
      - doctest-discover
